import { About } from '@/components/about';
import { Footer } from '@/components/footer';
import { Nav } from '@/components/nav';
import { Projects } from '@/components/projects';
import { Work } from '@/components/work';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Steven Lockhorst</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Nav />
        {/* about */}
        <About />
        {/* work experience */}
        <Work />
        {/* projects */}
        <Projects />
      </main>

      <Footer />
    </>
  );
}
